### ISSUE TITLE
[v5.4.0] How do I connect to the eks cluster of aws?

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#1113]
**Describe the bug**
The KubeConfig obtained by the eks cluster is not the same as the k8s cluster built by itself (see below). After adding, it shows "offline" (see screenshot), confirming that the network is normal. Does it not support eks? what should I do? Thanks!

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01Ea3hPREV5TkRRd09Gb1hEVE13TURreE5qRXlORFF3T0Zvd0M2NzAKZ0hKcmZTU1pRYU1kVndJazhxbmpMVG14d2JMd1VwQXIzSUtUSDZUUlF1SkNZakJ6eUNKMmhGYnp3WmVPMjlqZApFTVpqWjVBeGVhaUcydWZ3NFE4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEM2NzAKZ0hKcmZTU1pRYU1kVndJazhxbmpMVG14d2JMd1VwQXIzSUtUSDZUUlF1SkNZakJ6eUNKMmhGYnp3WmVPMjlqZApFTVpqWjVBeGVhaUcydWZ3NFE4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEM2NzAKZ0hKcmZTU1pRYU1kVndJazhxbmpMVG14d2JMd1VwQXIzSUtUSDZUUlF1SkNZakJ6eUNKMmhGYnp3WmVPMjlqZApFTVpqWjVBeGVhaUcydWZ3NFE4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEM2NzAKZ0hKcmZTU1pRYU1kVndJazhxbmpMVG14d2JMd1VwQXIzSUtUSDZUUlF1SkNZakJ6eUNKMmhGYnp3WmVPMjlqZApFTVpqWjVBeGVhaUcydWZ3NFE4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFE9MaDVISFVhdzhDdUhHazJacExwTm02QjRaVW8reWJyWjl5aWNBS3RzNDVMb1pvVHpXUkFOT1gvMUZtbHgKQnZ5eGVBRDVLNjVLYm9JcWJCbnNYZHNQTWk0bzk3Wmc4ZnFLRUdYN0I1dTJ5Z0Z3VFFlWUxiOTVKYTV2UGRTWAovYUJCUUM3Yk5HalQzNU85N0JVQjVSOEJuZmMwRVFMcVF3N3Q3M3dYUTFGUHVYaDArYUdLSHY0cmM2ST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://5V6HYAF93I937TL1G1SJUH7NOFKUMV6B.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:888888888888:cluster/eks-rainbond-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:888888888888:cluster/eks-rainbond-cluster
    user: arn:aws:eks:us-east-1:888888888888:cluster/eks-rainbond-cluster
  name: arn:aws:eks:us-east-1:888888888888:cluster/eks-rainbond-cluster
current-context: arn:aws:eks:us-east-1:888888888888:cluster/eks-rainbond-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:888888888888:cluster/eks-rainbond-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - eks-rainbond-cluster
      command: aws
```

**Screenshots**
![image](https://user-images.githubusercontent.com/53854600/140450219-951db3eb-532e-49df-8509-410f14ba4b9f.png)

**The relevant information:**
 - Rainbond Version [5.4.0]
 - Kubernetes version [1.21]
