### ISSUE TITLE
.net core 源码构建无法启动

### ISSUE THREAD

**Issue by zzzhangqi** [goodrain/rainbond#1142]
使用 .net core 源码构建的应用无法运行，报错启动命令不对
查看默认构建POD的yaml文件发现：
```
spec:
  containers:
  - args:
    - start
    - web
```
这个args参数是不正确的，不应该存在

目前临时解决的办法，可通过 [rainbondfile](https://www.rainbond.com/docs/component-create/language-support/rainbondfile/) 修改cmd
