### ISSUE TITLE
插件的命令行中配置环境变量不生效问题

### ISSUE THREAD

**Issue by pescox** [goodrain/rainbond#1185]
创建插件，使用Dockerfile方式，并且命令行中包含需要配置的环境变量。组件运行起来环境变量不生效。如下图：
![image](https://user-images.githubusercontent.com/33922888/169185458-0be96e7e-3aed-4dc7-a912-a4ef94daf259.png)
初始化容器运行起来之后直接打印的是$MYNAME，而不是配置的值

Rainbond版本：5.6.0以下版本

**Comment by yangkaa** [comment]
初始化容器中该环境变量是否被成功注入？即对应 yaml 文件中有该变量吗

**Comment by pescox** [comment]
> 初始化容器中该环境变量是否被成功注入？即对应 yaml 文件中有该变量吗

成功注入，有该变量。 图例中的echo $NAME会被解析成：
```yaml
          args:
            - echo
            - $MYNAME
```
没有经过shell format，这会直接打印$MYNAME
需要解析成
```yaml
          command: 
            - /bin/sh
            - -c
          args:
            - echo $MYNAME
```
