### ISSUE TITLE
对接公有云k8s集群后，创建应用组件，由于chaos调用集群内的docker-api与其版本不符，而导致无法创建应用。报错如下：

### ISSUE THREAD

**Issue by yangkaa** [goodrain/rainbond#1213]
Build app version from source code failure,list images: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39

**Comment by dazuimao1990** [comment]
临时的解决方案，是为 rbd-chaos 组件添加环境变量： DOCKER_API_VERSION=1.39

操作方式：
```bash
kubectl edit rbdcomponent rbd-chaos -n rbd-system
```
在 spec 下添加：
```yaml
spec:
  env:
  - name: DOCKER_API_VERSION
    value: "1.39"
```
