### ISSUE TITLE
新建应用报异常

### ISSUE THREAD

**Issue by allenonline** [goodrain/rainbond#128]
[3.7.1 ] Rainbond versions
    [centos 7.3 ] Operating system and kernel
    [kvm in smartos ] Provider(Aliyun,VirtualBox,...)
    [ Online/Single node] Install details(Online/Offline,Single node/HA)
    Steps to reproduce

第一次使用，在参考demo
源代码地址：https://github.com/goodrain/dockerfile-demo.git
进行基于源码的新建应用时出错。界面显示
“应用检测未通过
请核对并修改以下信息后，再重新检测。
获取代码失败 请确认仓库能否正常访问，或联系客服咨询”

在容器rbd-app-ui内可以ping通地址github.com
跟踪/opt/rainbond/logs/rbd-app-ui/goodrain.log
看到的异常是

`2018-09-27 11:07:16 [DEBUG] localhost [wrapper] /app/ui/goodrain_web/decorator.py:18 perf :: class RegionInvokeApi, function _request, cost_time 0.0260219573975
2018-09-27 11:07:16 [DEBUG] localhost [wrapper] /app/ui/goodrain_web/decorator.py:18 perf :: class RegionInvokeApi, function _request, cost_time 0.0173561573029
2018-09-27 11:07:16 [DEBUG] localhost [wrapper] /app/ui/goodrain_web/decorator.py:18 perf :: class RegionInvokeApi, function _request, cost_time 0.0159499645233
2018-09-27 11:07:36 [DEBUG] localhost [create_source_code_app] /app/ui/console/services/app.py:115 service.create :: user:admin create service from source code
2018-09-27 11:07:36 [DEBUG] localhost [wrapper] /app/ui/goodrain_web/decorator.py:18 perf :: class RegionInvokeApi, function _request, cost_time 0.0515398979187
2018-09-27 11:07:36 [DEBUG] localhost [wrapper] /app/ui/goodrain_web/decorator.py:18 perf :: class RegionInvokeApi, function _request, cost_time 0.0143179893494
2018-09-27 11:07:36 [DEBUG] localhost [get] /app/ui/console/views/app_create/app_check.py:58 start save check info ! checking
2018-09-27 11:07:36 [DEBUG] localhost [get] /app/ui/console/views/app_create/app_check.py:74 check result = {u'check_status': u'failure', u'service_info': [{u'procfile': False, u'language': u'', u'envs': None, u'image': {u'tag': u'latest', u'name': u'goodrain.me/runner'}, u'args': [u'start', u'web'], u'ports': None, u'dependencies': False, u'volumes': None, u'memory': 0, u'runtime': False, u'image_alias': u''}], u'error_infos': [{u'error_type': u'FatalError', u'solve_advice': u'\u8bf7\u786e\u8ba4\u4ed3\u5e93\u80fd\u5426\u6b63\u5e38\u8bbf\u95ee\uff0c\u6216\u8054\u7cfb\u5ba2\u670d\u54a8\u8be2', u'error_info': u'\u83b7\u53d6\u4ee3\u7801\u5931\u8d25'}]}`

不知要如何解决这个问题？

**Comment by ysicing** [comment]
获取代码错误,你在宿主机和rbd-chaos内git clone这个项目看能否git clone

**Comment by allenonline** [comment]
找到原因了，还是dns的问题。
在rbd-chaos内修改/etc/resolv.conf
加上公共dns地址8.8.8.8 后可以正常获取代码了。
那么问题就回到了dns设置的问题，我现在所有的容器内
```
bash-4.3# cat /etc/resolv.conf
nameserver 10.16.3.11
```
nameserver 默认只有宿主机ip。此时访问rainbond的内部域名如goodrain.me，repo.goodrain.me是可以的，但所有的外网域名都不能访问。不知道是不是rbd-dns的问题，按照rainbond工程师的说明“rbd-dns上有当前默认dns和1.2.4.8”，通过1.2.4.8也是可以访问外网域名的，但明显没有生效。
不知道要如何处理，现在很多操作失败，我又无法确定是调用的哪个容器的服务，手动一个个去容器内修改/etc/resolv.conf，太麻烦还不能保存配置。。。

**Comment by ysicing** [comment]
你可以看看rbd-dns的配置上游源， 手动测试 `dig @<宿主机ip> github.com +short`

**Comment by allenonline** [comment]
执行 dig @<宿主机ip> github.com +short
没有返回值，要怎么处理呢？

**Comment by allenonline** [comment]
```
- name: local-dns
  health:
    name: local-dns
    model: cmd
    address: /opt/rainbond/health/local-dns.sh
    time_interval: 5
  after:
    - network.target
  requires:
    - network.target
  type: notify
  start: none
  restart_policy: always
  restart_sec: 10
- name: rbd-dns
  endpoints:
  - name: DNS_ENDPOINTS
    protocol: udp
    port: 53
  health:
    name: rbd-dns
    model: cmd
    address: /opt/rainbond/health/rbd-dns.sh
    time_interval: 5
  after:
    - docker
  type: simple
  pre_start: docker rm rbd-dns
  start: >-
    docker run --name rbd-dns
    --network host
    --memory 1024M
    -e VERBOSE=true
    -v /opt/rainbond/etc/kubernetes/kubecfg:/opt/rainbond/etc/kubernetes/kubecfg
    -i goodrain.me/rbd-dns:3.7
    --kubecfg-file=/opt/rainbond/etc/kubernetes/kubecfg/admin.kubeconfig
    --v=2
    --healthz-port=8089
    --dns-bind-address=10.16.3.11
    --nameservers=10.16.1.20,1.2.4.8
    --recoders=goodrain.me=10.16.3.11,*.goodrain.me=10.16.3.11
  stop: docker stop rbd-dns
  restart_policy: always
  restart_sec: 10

```
