### ISSUE TITLE
Rainbond 插件机制设计

### ISSUE THREAD

**Issue by yangkaa** [goodrain/rainbond#1480]
# 目的
1. 实现微内核，平台完整功能通过插件扩展，便于开源生态扩展
2. 通过插件体系，开发者方便共享代码
3. 精简安装，按需扩展功能
4. 支持 K8s 中一些能力的扩展或编辑

# 设计思路
<div align="center">
<img src=https://user-images.githubusercontent.com/30614084/206634321-7de9feda-6b6a-4430-a389-f2d6717d6bcf.jpg width=50% />
</div>

当前可以规划的插件大概有大屏系统、监控系统、工作流、安全类系统或源码构建系统。

插件设计当前会有以下两种思路：
1. UI 扩展、后端接口扩展。即 UI 和后端接口都提供可扩展的方式。开发插件时可以自定义 UI 和后端接口，优势是灵活性极高，能满足用户对 UI 的一些定制化，但是开发难度高，无法复用已有的体系。
2. 将插件作为一种特殊类型的应用进行部署，平台识别到后统一查看管理。优势是能尽可能的复用我们应用市场。对于用户制作，也可以复用已有的应用市场能力。

扩展能力主要是指如何能复用已有的 Kubernetes 上的一些能力，实现功能的扩充，可以理解为能力是 K8s 中标准实现，通过平台能直接编辑，与集群资源同步。

# 最终效果
1. 插件统一存放到应用市场，可以从应用市场安装和升级

2. 有插件配置页面
- 用户自行实现插件发布后，可以在平台被识别出来
- 被识别出来的插件，可以通过界面进行查看
- 官方实现的插件安装后可以触发平台对应页面，或支持进行配置二级菜单

4. 支持多种 ServiceMesh 框架的注入和使用。支持用户使用自己的 GatewayAPI 实现，支持用户自定义想要直接在平台上编辑的能力。

# 业务流程
## 插件
![plugin流程图](https://user-images.githubusercontent.com/30614084/206635245-ab9e88b5-4277-4279-9556-24fbfa83d891.jpg)

用户安装插件，分为官方插件/非官方插件：官方插件会在UI上展示隐藏入口；非官方插件则不会。

1. 用户在应用级别管理插件的各类参数配置
2. 用户在平台管理页面，全局管理各个集群下的插件信息，可以跳转到应用下或者直接访问

![image](https://user-images.githubusercontent.com/30614084/206635504-f0bd0be9-e00b-4765-92ef-10031f31461b.png)

## 扩展能力
![ability 流程图](https://user-images.githubusercontent.com/30614084/206635682-c814e41b-5d7c-4aec-b7d9-a684b02b4f18.jpg)

平台管理员在集群中部署 CRD 资源（定义Rainbond 需要 Watch 的资源类型），控制台可以看到对应资源组的全部资源。

如果 Watch 到的资源类型与平台集成，则可以在页面上配置对应的参数。如应用治理模式、GatewayClass等资源。

如果不能与平台集成，那么在该页面只能直接编辑 yaml 文件修改。

![image](https://user-images.githubusercontent.com/30614084/206635842-88c01877-2711-4aae-807c-e6ede1a8c41a.png)
![image](https://user-images.githubusercontent.com/30614084/206635880-f4c2a502-c100-4c3e-9ddf-bb2d0670224f.png)

# 技术实现
## 插件
<div align="center">
<img src=https://user-images.githubusercontent.com/30614084/206636142-1c6c983d-b99a-4b7a-8fa1-9711e69b1652.jpg width=40% />
</div>

1. 用户安装插件以后，会创建出两类资源：
- Rainbond应用模版：插件本身就是一个应用，该应用提供完整能力
- RainbondPluginCR：Rainbond 的插件定义 CR 资源，主要包括插件的元数据（用于页面展示）、插件类型（可根据平台功能进行拆分，如构建类型插件【平台构建组件】、展示类型插件【大屏】等）、插件作者信息等
2. Console 会调用 rbd-api 的接口，获取当前可用的插件资源以及安装状态。插件资源只有安装了才会在页面显示。插件需要分集群展示，通过切换集群，可以看到某个集群内拥有的插件。部署多套时，插件会展示多个。

```yaml
apiVersion: rainbond.io/v1alpha1
kind: RainbondPlugin
spec:
  name: large-screen
  description: This is Linkerd Plugin
  pluginType: Monitor # Custom
  author: "goodrain"
```

## 扩展能力
![ability 实现流程图](https://user-images.githubusercontent.com/30614084/206636964-39488baa-4a16-4d5c-9036-322042f01b2f.jpg)
1. 用户可以自己在集群中创建 RainbondAbilityCR 资源，该资源可以定义需要 Watch 的资源类型。
2. 控制台会去查询所有 RainbondAbilityCR 中需要 Watch 的资源，在扩展能力处展示出来相关资源，此处资源和 K8s 集群同步，可以进行修改操作。不允许删除。

### ServiceMesh能力的使用
```yaml
apiVersion: rainbond.io/v1alpha1
kind: RainbondAbility
spec:
  name: ServiceMesh
  description: "xxxxx"
  watchGroups:
    - apiVersion: rainbond.io/v1alpha1
      kind: RBDServiceMesh

      
apiVersion: rainbond.io/v1alpha1
kind: RBDServiceMesh
spec:
  name: linkerd
  description: "xxxxx"
  inject:
    - method: label # label/annotation
      key: istio/enable-sidecar
      value: "true"
```
需要两类CRD资源，RainbondAbility 和 RainbondServiceMesh。
1. 可以在 RainbondServiceMesh CR 资源中定义 ServiceMesh 框架的注入方式以及描述。
2. RainbondAbility 定义需要 watch RainbondServiceMesh 资源，这样第一步创建出来的资源即可在页面中编辑，同时能触发控制台治理模式切换功能。

### GatewayAPI能力的使用
1. 部署 RainbondAbility 资源，定义需要 watch 的资源类型，平台管理-能力就会列出 GatewayClass 所有资源，eg: envoy
```yaml
apiVersion: rainbond.io/v1alpha1
kind: RainbondAbility
spec:
  name: gateway
  description: "xxxxx"
  watchGroups:
    - apiVersion: gateway.networking.k8s.io/v1beta1
      kind: GatewayClass
```
2. 用户在集群中安装 envoy Gateway，此时会生成 gatewayClass 资源
4. 用户在网关页面，添加策略时，可以选择对应的 网关实现，选择 envoy。参数只支持标准的 Gateway HttpRoute 、TCPRoute 。
5. 当应用运行起来后，生成的资源类型不再是 ingress，而是 Gateway 和 HttpRoute 资源。

# 插件规划
- [ ] 插件基础框架
- [ ] 功能扩展
  - [ ] 流水线
  - [ ] CI能力扩展
    - [ ] 自动测试
    - [ ] 代码静态检查
  - [ ] CD能力扩展
    - [ ] 金丝雀发布/AB测试
    - [ ] 流程审核
- [ ] 可观测能力扩展插件
  - [ ] 收集插件
  - [ ] 展示插件
- [ ] Service Mesh框架插件
  - [ ] Linkerd
  - [ ] dapr
  - [ ] 其他支持Sidecar注入的治理框架
- [ ] 网关插件
  - [ ] Higress
  - [ ] Envoy  Gateway
  - [ ] 其他支持Gateway API的实现
- [ ] 设备插件（以DeamonSet的方式运行）
  - [ ] GPU
  - [ ] 其他需要跟硬件结合的驱动
- [ ] Cloud provider（通过API自动对接云平台）
  - [ ] 阿里云 ACK 
  - [ ] 华为云 CCE
- [ ] Workload类型扩展插件(在现有应用模型上支持扩展)
  - [ ] Knative
  - [ ] Volcano
- [ ] 边缘计算支持（安装/对接/应用分发特殊支持）
  - [ ] kubedge
  - [ ] SuperEdge
- [ ] 安全和策略插件（扩展安全能力）
- [ ] 存储插件（对接存储的能力）
