### ISSUE TITLE
安装rainbond对接ceph存储后，默认无状态组件使用共享存储（文件）创建失败

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1620]
**Describe the bug**
安装rainbond对接ceph后，默认无状态组件使用共享存储（文件）创建失败，发现使用的sc是[rainbondsssc]，当修改成有状态组件并使用ceph存储后，可以正常运行，不知道这是不是一个bug，如果不是想知道如何修改默认的为ceph存储

**Screenshots**
对接的时候已经设置了下面的RWO和RWX为ceph
![image](https://user-images.githubusercontent.com/36958251/231182438-17063bba-1ca0-4c8c-ab08-f5b5439d5cfb.png)
使用默认共享存储报错
![image](https://user-images.githubusercontent.com/36958251/231182630-3034ddc9-a8ac-4ab9-9424-ddb780046615.png)

**The relevant information:**
 - Rainbond Version [e.g. 5.2.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by yangkaa** [comment]
当底层存储是 Ceph 时，使用平台默认的共享存储，那么共享存储只能以子目录的形式挂载。所以需要修改 rbd-api 和 rbd-worker ，增加环境变量 ENABLE_SUBPATH=true。

1. 修改 rbd-api 资源
```bash
kubectl edit rbdcomponent rbd-api -n rbd-system
```
2. 增加环境变量
```yaml
spec:
  env:
  - name: ENABLE_SUBPATH
    value: "true"
```
3. 修改 rbd-worker 资源
```bash
kubectl edit rbdcomponent rbd-api -n rbd-system
```
4. 增加环境变量
```yaml
spec:
  env:
  - name: ENABLE_SUBPATH
    value: "true"
```
完成以上步骤后，挂载共享存储的组件应该可以正常工作

**Comment by lihao6666** [comment]
您好，按照你的说明进行操作了，并没有生效，我猜测我现在的问题不是挂载失败的问题，而是默认共享存储(文件)的sc不是系统使用的ceph，而是系统默认的rainbondsssc

**Comment by yangkaa** [comment]
上面第三步命令敲错了，应该是改 rbd-worker。
```
kubectl edit rbdcomponent rbd-worker -n rbd-system
```

**Comment by lihao6666** [comment]
> 上面第三步命令敲错了，应该是改 rbd-worker。
> 
> ```
> kubectl edit rbdcomponent rbd-worker -n rbd-system
> ```

嗯，这个我知道，但是还是没用，和之前一样的报错

**Comment by yangkaa** [comment]
你可以在修改完上面那些资源后，新建一个无状态组件，增加共享存储，启动。

然后提供以下信息便于排查：
1. rbd-worker 的日志
2. 该无状态组件的 yaml 
3. 该无状态组件的 pv、pvc yaml文件
4. kubelet 的日志信息

**Comment by lihao6666** [comment]
你好，根据你的需要整理了一些结果，可以通过下面链接查看文档[](https://fqing-oss.oss-cn-beijing.aliyuncs.com/%E5%85%B6%E5%AE%83/question.md)

**Comment by yangkaa** [comment]
在你提供的无状态组件yaml中，存储是这样挂载的。
```yaml
volumeMounts:
  - name: manual38
    mountPath: /nginx/data
```

但是在 5.13.0 版本中，如果在 rbd-api 和 rbd-worker 中都存在环境变量 `ENABLE_SUBPATH`，且值为 `true`，那么无状态组件存储yaml应该是如下所示：
```yaml
volumeMounts:
  - name: manual38
    mountPath: /nginx/data
    subPath: tenant/xxxx/services/xxxx
```

在这种情况下，应该不会出现挂载失败的问题
