### ISSUE TITLE
基于原生k8s非标准安装接入的问题

### ISSUE THREAD

**Issue by nAnderYang** [goodrain/rainbond#1729]
由于原生集群安装未使用默认的6443 和ip 这里引入了域名+自定义端口的结构
导致无法在增加k8s集群时无法正确的被添加

比如 这里的集群config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {hidden}
    server: https://custom.something.domain:12345
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: {hidden}
    client-key-data: {hidden}
```

![image](https://github.com/goodrain/rainbond/assets/28423384/40883987-8004-428c-89d8-b9f239907927)

请问下 我要怎么解决这么问题？

**The relevant information:**
 - Rainbond Version [v5.15.0-release-7b54c4046-2023-07-29-16-allinone]
 - Browser [chrome]
 - Kubernetes version [v1.23.1]
