### ISSUE TITLE
support default storageclass 

### ISSUE THREAD

**Issue by willzhang** [goodrain/rainbond#1740]
**Is your feature request related to a problem? Please describe.**

There already have  a default storageclass in my kubernetes cluster

```
$ kubectl get sc
NAME                                     PROVISIONER         RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-hostpath (default)               openebs.io/local    Delete          WaitForFirstConsumer   false                  31d
```

 i want use the default storageclass with helm install rainbond, how can i do that?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
rainbond使用的存储好混乱，要求安装NFS 客户端，自己创建了2个存储类manual和rainbondvolumerwx，还是用rwx和rwo两种存储类型。

大多数helm chart的存储设计这样比较简单合理：
```
persistence:
  ## @param persistence.enabled Enable persistence
  ##
  enabled: true
  ## @param persistence.storageClass PVC Storage Class for Tomcat volume
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
```
