### ISSUE TITLE
调整 Kaniko 构建参数异常

### ISSUE THREAD

**Issue by anhao** [goodrain/rainbond#1778]
调整 kaniko 镜像加速 后 chaos 提示 unknown flag: --kaniko-args

**To Reproduce**

**Screenshots**
![image](https://github.com/goodrain/rainbond/assets/9844218/cb84cd61-402a-49c6-9005-450b8e118506)

![image](https://github.com/goodrain/rainbond/assets/9844218/16e1ec61-350a-480b-922a-5622ad4975ad)

**The relevant information:**
v5.15.2-release-ff32a0912-2023-09-10-15

**Comment by yangkaa** [comment]
在 5.15.2 版本中，已经弃用了 kaniko 构建，使用 buildkit 构建。如果你需要配置镜像加速。可以参考以下步骤：

1. 找到镜像仓库的配置文件，通常在 rbd-system 命名空间下，如果你使用的内置镜像仓库，应该是一个 goodrain-me 的 configmap。如果你更换了外部镜像仓库，应该是外部镜像仓库的域名，中间以“-”分割。

```bash
kubectl get cm -nrbd-system
```

2. 编辑这个 Configmap
```bash
kubectl edit cm goodrain-me -nrbd-system
```

3. 修改为如下配置，其中 mirrors 是镜像加速的地址
```yaml
apiVersion: v1
data:
  buildkittoml: |-
    debug = true
    [registry."goodrain.me"]
      http = false
      insecure = true
    [registry."docker.io"]
      mirrors = ["192.168.18.145"]
kind: ConfigMap
metadata:
  name: goodrain.me
  namespace: rbd-system
```
