### ISSUE TITLE
ComposeFile解析错误 请确认ComposeFile输入是否语法正确  docker-compose报错

### ISSUE THREAD

**Issue by zhangjun050754** [goodrain/rainbond#186]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ ] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [ ] Operating system and kernel

- [ ] Provider(Aliyun,VirtualBox,...)

- [ ] Install details(Online/Offline,SingleNode/HA)

**Comment by barnettZQG** [comment]
如方便，请提供docker compose文本内容

**Comment by zhangjun050754** [comment]
```
version: "2.1"
services:
  demo:
    image: goodrain.me/runner:latest
    container_name: demo
    restart: always
    network_mode: host
    volumes:
    - __GROUP_DIR__/demo/v1.0_20190107020156.tgz:/tmp/slug/slug.tgz
    command: start web
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: "2"
```
导出最简单的demo的docker compose填进去不行，这块该怎么写 文档里面没有找到
能否提供docker compose的示例我试一下

**Comment by GLYASAI** [comment]
你好, Rainbond 目前支持的docker compose文件的version只有1, 2, 3. 不支持2.1, 而且最好使用 versoin:"3".

下面是一个 version: '3' 的示例, 是docker compose官网的一个示例: [Compose and WordPress](https://docs.docker.com/compose/wordpress/)
```
version: '3'  # 由 3.3 改成 3

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data: {}
```

另外, 我们会在近期完善docker compose的文档. 谢谢.
