### ISSUE TITLE
大镜像文件无法构建

### ISSUE THREAD

**Issue by PDMoFan** [goodrain/rainbond#2139]
创建组件的时候选择镜像容器，填写完配置后点击构建，大镜像文件(10G和16G)都无法构建，会卡在推送镜像到默认私有仓库这一步

环境：
快速安装6.1.1版本rainbond

**Comment by zzzhangqi** [comment]
这是由于默认的镜像仓库（registry）对接了 Minio 引发的问题，同时还发现在 registry v2 release 版本中无法对镜像进行 [GC 清理](https://github.com/distribution/distribution/issues/4382)，因此在下个版本(v6.1.2-release)会将默认对接的存储切换到本地存储。

临时将默认的镜像仓库从存储到 Minio 切换到本地存储如下：

1. 更新 `rainbond-operator` 镜像至 `v6.1.2-pre` 版本
```yaml
$ kubectl edit deploy rainbond-operator -n rbd-system

...
spec:
...
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator:v6.1.2-pre
```

2. 获取自动创建的 `rbd-hub` pv 本地路径
```yaml
$ kubectl get pv | grep "rbd-system/rbd-hub" | awk '{print $1}' | xargs kubectl get pv -o yaml

apiVersion: v1
kind: PersistentVolume
...
spec:
  ...
  hostPath:
    path: /opt/rainbond/local-path-provisioner/pvc-926fab85-d8c1-4699-aab0-4e45c610997b_rbd-system_rbd-hub
    type: DirectoryOrCreate
  ...
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 172.17.1.23
  ...
```

> [!TIP]
> 如果旧镜像数据不需要了，下述步骤可以不执行。

3. 安装 Minio Client 工具 Mc
```bash
curl https://dl.minio.org.cn/client/mc/release/linux-amd64/mc --create-dirs -o /bin/mc
chmod +x /bin/mc
```

4. 获取 Minio Service IP
```bash
kubectl get svc -n rbd-system | grep minio-service
```

5. 从 Minio 中拷贝数据到本地存储（在`172.17.1.23`节点执行）
```bash
mc alias set myminio http://10.43.61.29:9000 admin admin1234
mc mirror myminio/rbd-hub /opt/rainbond/local-path-provisioner/pvc-926fab85-d8c1-4699-aab0-4e45c610997b_rbd-system_rbd-hub
```
