### ISSUE TITLE
🐞 反馈问题：helm配置内网https镜像仓库安装rainbond后，页面提示数据中心操作故障

### ISSUE THREAD

**Issue by KeKouShi** [goodrain/rainbond#2152]
### 请先确认以下事项：

- [x] 请务必查看[常见问题](https://www.rainbond.com/docs/faq)和[故障排除](https://www.rainbond.com/docs/troubleshooting)
- [x] 在 [issues](https://github.com/goodrain/rainbond/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [x] Rainbond 已升级到 [最新版本](https://github.com/goodrain/rainbond/releases)

### 问题描述

1. helm安装rainbond，所配置为内网https镜像仓库，安装完成后，页面提示
数据中心操作故障 {'apitype': 'Not specified', 'url': 'https://rbd-api-api:8443/v2/tenants/default/image-repositories?namespace=default', 'method': 'GET', 'httpcode': 503, 'body': {'error': '部分服务不可用'}}
2. rbd-chaos组件报错
level=error msg="create hub client failed, try time is 10,registry url http:

### 该问题是否可以稳定重现？

可重现

### 重现步骤

rainbond镜像上传https镜像仓库
配置外部镜像仓库安装rainbond

### 截图

![Image](https://github.com/user-attachments/assets/db8c6252-b26c-41da-96c6-c6d563e8b84c)

![Image](https://github.com/user-attachments/assets/bc728edd-9fa7-4edb-9045-2cd736e891b0)

### 日志

 level=error msg="create hub client failed, try time is 10,registry url http://idt.ccwork.com:8076: Get \"http://*******/v2/\": http: non-successful response (status=400 body=\"<html>\\r\\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\\r\\n<body>\\r\\n<center><h1>400 Bad Request</h1></center>\\r\\n<center>The plain HTTP request was sent to HTTPS port</center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n\")"

### 期望结果

可以正常添加组件

### 操作系统 && Rainbond 版本

openEuler 22.03 k3s v6.1.1-release

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by zzzhangqi** [comment]
@KeKouShi domain 字段不需要携带 https http 等协议

**Comment by KeKouShi** [comment]
@zzzhangqi domain 字段不带https或http也是相同的报错

**Comment by zzzhangqi** [comment]
@KeKouShi 你的镜像仓库协议是 http 还是 https，仓库类型是 harbor 还是 docker registry

**Comment by KeKouShi** [comment]
@zzzhangqi 镜像仓库协议是https，类型是harbor，使用helm安装时，就是从此仓库拉取的镜像

**Comment by zzzhangqi** [comment]
@KeKouShi 未复现问题。

我搭建了 Docker Registry 并自签发了私有证书，用 K3s 搭建的单机测试环境。如下：

1. 使用 Docker Registry  搭建本地私有镜像仓库
```bash
docker run -v /root/cert:/cert \
-e REGISTRY_HTTP_TLS_CERTIFICATE=/cert/cert.crt \
-e REGISTRY_HTTP_TLS_KEY=/cert/cert.key \
-p 5000:5000 \
-d registry:2.8
```
2. K3s 私有镜像仓库配置文件
```yaml
$ cat /etc/rancher/k3s/registries.yaml

configs:
  "10.64.0.7:5000":
    auth:
      username: admin
      password: admin1234
    tls:
      insecure_skip_verify: true
```

3. Rainbond `values.yaml` 配置文件
```yaml
$ cat values.yaml 
Cluster:
  gatewayIngressIPs: 10.64.0.7

  nodesForGateway:
  - externalIP: 10.64.0.7
    internalIP: 10.64.0.7
    name: iv-ydq6bajda8k36d19ye26
  nodesForChaos:
  - name: iv-ydq6bajda8k36d19ye26
  containerdRuntimePath: /var/run/k3s/containerd

  imageHub:
    enable: true
    domain: 10.64.0.7:5000
    namespace: rainbond
    username: admin
    password: admin
```

4. Rainbond Pod
```bash
$ kubectl get pod -n rbd-system
NAME                                      READY   STATUS    RESTARTS   AGE
local-path-provisioner-5476dcfbb8-wj6w5   1/1     Running   0          9m44s
minio-0                                   1/1     Running   0          9m47s
rainbond-operator-9b5876fcb-djg84         1/1     Running   0          9m50s
rbd-api-5bb68877f4-pw22s                  1/1     Running   0          9m29s
rbd-app-ui-587dd78fc4-2r66h               1/1     Running   0          8m42s
rbd-chaos-hk7fp                           1/1     Running   0          9m24s
rbd-db-0                                  1/1     Running   0          9m46s
rbd-gateway-7877b5f969-c8926              2/2     Running   0          9m43s
rbd-monitor-0                             1/1     Running   0          9m46s
rbd-mq-545d6748f5-v9zfq                   1/1     Running   0          9m46s
rbd-worker-6bdd5f86-9wsqg                 1/1     Running   0          9m41s
```

5. Rainbond 源码构建截图
![Image](https://github.com/user-attachments/assets/30bf9ef9-5fd8-4e72-a3bc-fec4a3e430e5)
