### ISSUE TITLE
如何使用内置的prometheus监控服务监控其他组件

### ISSUE THREAD

**Issue by linyx-7** [goodrain/rainbond#370]
内置的rbd-monitor可以监控好雨云自身状态，我如何想同时监控外部的数据库，mq，redis等服务，如何修改。直接修改容器/var/lib/**/diff/这下面的yml文件，服务重启后，会自动生成初始的prometheus.yml配置文件，应该如何添加新的target监控点。

**Comment by barnettZQG** [comment]
rainbond自身的监控系统目前不推荐用户手动配置，如果用户有监控的需求我们建议自行部署Prometheus服务。
在未来的版本中我们计划使监控系统支持收集平台内管理的服务（内部服务和第三方服务）的自定义Prometheus端点。

* 内部运行管理的应用

  内部运行的应用即运行于Rainbond集群内的应用，该应用类型用户业务层不提供指标的情况下天生具有资源占用（内存、CPU、IO、网络）和服务性能（吞吐率、响应时间、在线人数）等监控指标。用户自行开发的业务指标暴露端点采用元数据配置的方式告知Rainbond。

  * MONITOR_METRIC_PATH=/metric （指标暴露的HTTP请求路径）
  * MONITOR_METRIC_PORT=8080（指标暴露的HTTP监听端口，默认为应用的首个配置端口或别名为PROMETHEUS_CLIENT的端口）

  应用部署后一旦填写上诉配置，Rainbond将自动将其加入到自定义监控服务序列。

* 第三方应用

  第三方应用是指运行于Rainbond集群外的应用，比如Windows应用，客户端应用。Rainbond采用第三方服务的方式将其纳入应用管理列表，但其不具备内部运行服务所具有的天然监控指标。第三方服务支持以下配置来注册监控端点：

  - MONITOR_METRIC_PATH=/metric （指标暴露的HTTP请求路径）
  - MONITOR_METRIC_PORT=8080（指标暴露的HTTP监听端口，默认为应用的首个配置端口或别名为PROMETHEUS_CLIENT的端口）

  Rainbond将根据第三方服务配置的实例通信地址和上诉配置将服务加入到自定义监控服务序列。

**Comment by VectXi** [comment]
请问 MONITOR_METRIC_PATH，MONITOR_METRIC_PORT 这两个是配置环境变量吗？

**Comment by lxm** [comment]
经过调研，使用prom-operator和ServiceMonitor模式来实现此功能比较合适

一个经过测试的ServiceMonitor配置如下

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: region-tokenchecker
  namespace: default
spec:
  jobLabel: service_alias
  endpoints:
  - interval: 10s
    path: /metrics
    port: tcp-9090
    relabelings:
      - sourceLabels: [__address__]
        targetLabel: app_name
        replacement: "region-tokenchecker"
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      service_port: 9090
      port_protocol: http
      name: gr0a581fService
```
