### ISSUE TITLE
安装完成docker-compose.yaml配置文件不全

### ISSUE THREAD

**Issue by ysicing** [goodrain/rainbond#38]
```
version: '2.1'
services:
  rbd-proxy:
    image: rainbond/rbd-proxy:3.4
    container_name: rbd-proxy
    volumes:
    - /etc/goodrain/proxy/sites:/usr/local/tengine/conf/sites
    - /etc/goodrain/proxy/ssl:/usr/local/tengine/conf/ssl
    - /grdata:/grdata
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-app-ui:
    image: rainbond/rbd-app-ui:3.4
    container_name: rbd-app-ui
    environment:
      REGION_TAG: cloudbang
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
    volumes:
    - /etc/goodrain/console.py:/etc/goodrain/console.py
    - /grdata/services/console:/data
  rbd-slogger:
    image: rainbond/rbd-slogger:3.4
    command: basic_group
    container_name: rbd-slogger
    environment:
      REGION_TAG: cloudbang
    volumes:
    - /etc/goodrain/labor.py:/app/labor/etc/regions/cloudbang.py
    - /logs:/logs
    - /grdata:/grdata
    - /data/docker_logs:/data/docker_logs
    - /cache:/cache
    - /var/run:/var/run
    - /root/.docker/config.json:/root/.docker/config.json
    - /etc/goodrain/ssh:/home/rain/.ssh
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-dns:
    image: rainbond/rbd-dns:3.4
    container_name: rbd-dns
    environment:
    - KUBEURL=http://127.0.0.1:8181
    - FORWARD=100.100.2.136,100.100.2.138,114.114.114.114
    - SKYDNS_DOMAIN=goodrain.me
    - RECORD_1=goodrain.me:172.30.42.1
    - RECORD_2=lang.goodrain.me:172.30.42.1
    - RECORD_3=maven.goodrain.me:172.30.42.1
    - RECORD_4=config.goodrain.me:172.30.42.1
    - RECORD_5=console.goodrain.me:172.30.42.1
    - RECORD_6=region.goodrain.me:172.30.42.1
    - RECORD_7=kubeapi.goodrain.me:172.30.42.1
    - RECORD_8=download.goodrain.me:172.30.42.1
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
```
不全的配置文件
