### ISSUE TITLE
5.1.9手动创建k8s资源异常

### ISSUE THREAD

**Issue by fanyangyang** [goodrain/rainbond#589]
【BUG描述】(非BUG请删除本行)
kubectl create -f xxx.yaml报错
```
error: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup_v2): invalid object doesn't have additional properties
```
【部署环境】
- Rainbond版本(执行`grctl version`获取):v5.1.9-release-32cc2ba-2019-12-13-09
- 操作系统类型和版本:CentOS Linux release 7.6.1810 (Core)

k8s资源yaml文件
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
```

文件内容格式并非手写，而是拷贝而来，并且在其他集群中是可以正常创建的

网上搜索后找到相同的问题，怀疑是`metrics-server`中openapi生成格式有差异造成的
链接：https://www.bookstack.cn/read/kubernetes-practice-guide/troubleshooting-cases-schemaerror-when-using-kubectl-apply-or-edit.md
