### ISSUE TITLE
docker compose构建时第二个service检测问题

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#622]
【BUG描述】docker compose构建第二个service检测未通过

【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.1.9
- 操作系统类型和版本:ubuntu
- 离线部署/网络开放：开放

docker compuse构建时组件检测未通过，提示如下；mongo检测未通过。
![image](https://user-images.githubusercontent.com/50609288/71799450-4b00f800-3090-11ea-8bb4-3e3b2aaefe49.png)

docker compose文件如下

version: "2"
services:
  DOClever:
    image: lw96/doclever
    restart: always
    container_name: "DOClever"
    ports:
    - 10000:10000
    volumes:
    - /root/doclever/data/file:/root/DOClever/data/file
    - /root/doclever/data/img:/root/DOClever/data/img
    - /root/doclever/data/tmp:/root/DOClever/data/tmp
    environment:
    - DB_HOST=mongodb://mongo:27017/DOClever
    - PORT=10000
    links:
    - mongo:mongo

  mongo:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    ports:
    - 27017:27017
    volumes:
    - /root/doclever/data/db:/data/db

**Comment by barnettZQG** [comment]
@Aaron-23 上诉docker compose文件内容不是标准yaml格式。请提供正确格式的docker compose配置。
@fanyangyang  跟踪这个问题。

**Comment by Aaron-23** [comment]
yaml文件
```
version: "2"
services:
  DOClever:
    image: lw96/doclever
    restart: always
    container_name: "DOClever"
    ports:
    - 10000:10000
    volumes:
    - /root/doclever/data/file:/root/DOClever/data/file
    - /root/doclever/data/img:/root/DOClever/data/img
    - /root/doclever/data/tmp:/root/DOClever/data/tmp
    environment:
    - DB_HOST=mongodb://mongo:27017/DOClever
    - PORT=10000
    links:
    - mongo:mongo

  mongo:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    ports:
    - 27017:27017
    volumes:
    - /root/doclever/data/db:/data/db
```
